#include<conio.h>
#include<stdio.h>
void main()
{
	int a,b;
	clrscr();
	printf("\n Enter Value =");
	scanf("%d",&a);
	printf("\n Enter Value =");
	scanf("%d",&b);
	a>b?printf("\na is>"):
	a==b?printf("\n A=B"):printf("\n B is>");
	getch();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
}